AllCops:
  TargetRubyVersion: 2.7.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'Gemfile'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - test/**/*

Metrics/ClassLength:
  Exclude:
    - test/**/*